#!/bin/python3

from turtle import *

color("deepskyblue")
begin_fill()
forward(200)
right(90)
forward(120)
right(90)
forward(200)
end_fill()
right(90)
forward(80)
right(90)

color("gold")
begin_fill()
forward(200)
right(90)
forward(40)
right(90)
forward(200)
end_fill()
right(90)
forward(80)
right(120)

color("black")
begin_fill()
forward(120)
right(120)
forward(120)
end_fill()
